### ISSUE TITLE
I said fix it

### ISSUE THREAD

**Issue by s0urfruit** [coserei/coserei.github.io#8]
### do this for the love of god
1. Create a `css/` directory 
2. Put `main.dark.css` in `css/`
3. Rename `main.css` to `main.light.css`
4. Put `main.light.css` in `css/`
5. Create a `assets/` directory
6. Put `indihome.mp3` in `assets/`

**Comment by coserei** [comment]
MATE, I GET 6 WEEKS OF SUMMER BREAK A YEAR, STOP BOTHERING ME WHEN I ACTUALLY HAVE TIME FOR LIVING MY DAMN LIFE
